title: CoMPhy Lab
description: Computational Multiphase Physics Laboratory
baseurl: ""
url: "https://comphy-lab.org"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag

# Site settings
permalink: /:title/

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name
  teaching:
    output: true
    permalink: /:collection/:name

# Exclude from processing
exclude:
  - scripts/node_modules
  - scripts/temp_blog_repo
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - coverage
  - tests
  - jest.config.js
  - package*.json
  # AI/dev tooling files and directories (do not build or watch)
  - .cursor
  - .cursor/**
  - .claude
  - .claude/**
  - CLAUDE.md
