title: CoMPhy Lab
description: Computational Multiphase Physics Laboratory
baseurl: ""
url: "https://comphy-lab.org"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag

# Site settings
permalink: /:title/

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name
  teaching:
    output: true
    permalink: /:collection/:name

# Exclude from processing
exclude:
  - scripts/node_modules
  - scripts/temp_blog_repo
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache