title: CoMPhy Lab
description: Computational Multiphase Physics Laboratory
baseurl: ""
url: "https://comphy-lab.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Site settings
permalink: /:title/
paginate: 5
paginate_path: "/news/page:num/"

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name
  publications:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name 